data_generation:
  device_count: 200
  factory_count: 10
  job_count: 200000
  output_file: "generated_data.json"
  day: "2025-06-30"
  time_interval: 30
  job_run_time: 3600
  batch_size: 1000

databases:
  influxdb:
    url: "http://192.168.210.2:8086"
    token: "ipX7uq6r85YMd4nG6dhIMPMCsKffBGAqf-4uUaFPjI_gdWrlPB61SNadBt9UFB7YtVi9z2m9lIOQQfllPqW2Fg=="
    org: "testorg"
    bucket: "testbucket"

  tdengine:
    host: "192.168.210.2"
    port: 7041
    username: "root"
    password: "taosdata"
    database: "sensor_db"

  iotdb:
    host: "192.168.210.2"
    port: 4667
    username: "root"
    password: "root"

benchmark:
  ## concurrency_levels: [1, 5, 20, 50, 100]
  concurrency_levels: [20]
  query_duration_seconds: 60
  warmup_duration_seconds: 10
  report_interval:
